"use client";
import { Check, CreditCard, LoaderCircle, LockKeyhole, ShieldCheck, XCircle } from "lucide-react";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useApp } from "@/components/providers/app-provider";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { formatPrice, productConfig } from "@/config/product";
import { mockPaymentRepository } from "@/repositories/mock";
type State = "idle" | "redirecting" | "failed" | "cancelled";
const included = ["Complete eight-module curriculum", "Targeted Practice Mode", "French-first exam simulations", "Weakness and mistake tracking", "Progress and MPK Readiness", "Completion certificate eligibility"];
export function CheckoutView() { const router = useRouter(); const { state: appState, updateUser } = useApp(); const [status,setStatus] = useState<State>("idle"); const checkout = async () => { setStatus("redirecting"); const result = await mockPaymentRepository.checkout(); if (result === "success") { if (appState.user) updateUser({ ...appState.user, tier: "paid_student" }); router.push("/checkout/success"); } else setStatus(result); }; return <div className="grid gap-7 lg:grid-cols-[1fr_.7fr]"><div><Card><CardContent className="pt-6"><p className="eyebrow">Order summary</p><h1 className="mt-3 text-3xl font-bold">{productConfig.courseName}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">One-time purchase. Unlock the full current mock curriculum and learning tools.</p><ul className="mt-7 space-y-3">{included.map((item) => <li key={item} className="flex gap-3 text-sm"><Check className="size-5 shrink-0 text-primary" />{item}</li>)}</ul><div className="mt-8 flex items-center justify-between border-t pt-6"><span className="font-bold">Total</span><div className="text-right"><strong className="text-2xl">{formatPrice()}</strong><p className="text-xs text-muted-foreground">CAD · one time</p></div></div></CardContent></Card><div className="mt-5 flex gap-3 rounded-xl bg-muted p-4"><ShieldCheck className="size-5 shrink-0 text-primary" /><p className="text-xs leading-5 text-muted-foreground">Production payments will be completed on a PCI-compliant provider’s secure checkout. MPK Academy never stores card details in this frontend.</p></div></div><Card className="h-fit"><CardContent className="pt-6"><span className="grid size-11 place-items-center rounded-full bg-primary/10 text-primary">{status === "redirecting" ? <LoaderCircle className="size-5 animate-spin" /> : status === "failed" || status === "cancelled" ? <XCircle className="size-5 text-danger" /> : <LockKeyhole className="size-5" />}</span><h2 className="mt-5 text-xl font-bold">{status === "redirecting" ? "Opening secure checkout…" : status === "failed" ? "Payment was not completed" : status === "cancelled" ? "Checkout cancelled" : "Continue securely"}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{status === "idle" ? "This MVP simulates the external payment handoff. No card details will be requested." : status === "redirecting" ? "Please wait while the mock provider responds." : "Your access has not changed. Try again when you are ready."}</p><Button className="mt-6 w-full" size="lg" onClick={checkout} disabled={status === "redirecting"}><CreditCard className="size-4" />{status === "idle" ? "Continue to secure payment" : status === "redirecting" ? "Redirecting…" : "Try again"}</Button><p className="mt-4 text-center text-xs text-muted-foreground">Mock checkout simulation</p></CardContent></Card></div>; }
