"use client";
import { Clock3, Flag, Send } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useApp } from "@/components/providers/app-provider";
import { Button } from "@/components/ui/button";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { QuestionCard } from "@/features/assessment/question-card";
import { examQuestions } from "@/data/questions";

export function ExamSession() {
  const router = useRouter(); const { setState } = useApp(); const [index, setIndex] = useState(0); const [answers, setAnswers] = useState<Record<string,string>>({}); const [seconds, setSeconds] = useState(25 * 60);
  useEffect(() => { const timer = window.setInterval(() => setSeconds((value) => Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, []);
  const submit = () => { const correct = examQuestions.filter((question) => answers[question.id]?.trim().toLowerCase() === question.correctAnswer.toLowerCase()).length; const score = Math.round((correct / examQuestions.length) * 100); setState((current) => ({ ...current, lastExamScore: score, progress: { ...current.progress, simulationsCompleted: current.progress.simulationsCompleted + 1, simulationAverage: Math.round((current.progress.simulationAverage + score) / 2) }, activities: [{ id: crypto.randomUUID(), label: "Exam simulation", detail: `${score}% overall`, timestamp: new Date().toISOString() }, ...current.activities] })); router.push("/exam/results"); };
  const question = examQuestions[index]; const minutes = Math.floor(seconds / 60).toString().padStart(2,"0"); const secs = (seconds % 60).toString().padStart(2,"0");
  return <div className="min-h-screen bg-[#f5f3ed] text-[#17251f] dark:bg-[#0d1411] dark:text-white"><header className="sticky top-0 z-20 border-b bg-inherit"><div className="mx-auto flex h-16 max-w-6xl items-center justify-between px-4"><div><p className="text-xs font-bold uppercase tracking-widest text-[#8d3438] dark:text-[#ef989b]">Simulation d’examen</p><p className="text-sm font-semibold">Compréhension</p></div><div className="flex items-center gap-2 rounded-lg border px-3 py-2 font-mono font-bold" aria-live="polite"><Clock3 className="size-4" />{minutes}:{secs}</div></div></header><main className="mx-auto max-w-6xl px-4 py-7"><div className="flex items-center justify-between text-sm"><span>Question {index + 1} sur {examQuestions.length}</span><span>{Object.keys(answers).length} réponses</span></div><Progress value={((index + 1) / examQuestions.length) * 100} label="Progression de l’examen" className="mt-3" /><div className="mt-7 grid gap-7 lg:grid-cols-[1fr_14rem]"><div className="rounded-2xl border bg-card p-5 sm:p-8"><QuestionCard exam question={question} value={answers[question.id]} onChange={(value) => setAnswers({ ...answers, [question.id]: value })} /></div><aside className="order-first lg:order-last"><div className="rounded-xl border bg-card p-4"><p className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Navigation</p><div className="mt-4 grid grid-cols-8 gap-2 lg:grid-cols-4">{examQuestions.map((item, itemIndex) => <button key={item.id} onClick={() => setIndex(itemIndex)} aria-label={`Question ${itemIndex + 1}${answers[item.id] ? ", answered" : ""}`} className={`grid aspect-square place-items-center rounded-lg border text-xs font-bold ${itemIndex === index ? "border-exam bg-exam text-white" : answers[item.id] ? "bg-muted" : "bg-card"}`}>{itemIndex + 1}</button>)}</div></div><p className="mt-4 flex gap-2 text-xs leading-5 text-muted-foreground"><Flag className="size-4 shrink-0" />Aucune aide pédagogique n’est disponible pendant la simulation.</p></aside></div><div className="mt-6 flex justify-between"><Button variant="secondary" disabled={index === 0} onClick={() => setIndex(index - 1)}>Précédent</Button>{index < examQuestions.length - 1 ? <Button onClick={() => setIndex(index + 1)}>Suivant</Button> : <Dialog><DialogTrigger asChild><Button><Send className="size-4" />Soumettre</Button></DialogTrigger><DialogContent><DialogTitle>Soumettre votre simulation ?</DialogTitle><DialogDescription>Vous avez répondu à {Object.keys(answers).length} questions sur {examQuestions.length}. Une fois soumise, la simulation ne peut plus être modifiée.</DialogDescription><div className="mt-6 flex justify-end gap-3"><DialogClose asChild><Button variant="secondary">Continuer l’examen</Button></DialogClose><Button onClick={submit}>Soumettre</Button></div></DialogContent></Dialog>}</div></main></div>;
}
