"use client";
import Link from "next/link";
import { ArrowRight, BookOpen, CalendarDays, Headphones, Info, TrendingUp } from "lucide-react";
import { useApp } from "@/components/providers/app-provider";
import { MetricBar, PageHeader } from "@/components/shared";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { competencies } from "@/data/mock-state";
import { calculateReadiness } from "@/lib/domain/readiness";
import { generateRecommendations } from "@/lib/domain/recommendations";
import { formatDate } from "@/lib/utils";

export function DashboardView() {
  const { state } = useApp(); const user = state.user; const readiness = calculateReadiness(state.progress); const recommendation = generateRecommendations(state.progress, state.mistakes)[0];
  return <><PageHeader eyebrow="Your preparation today" title={`Good morning, ${user?.firstName ?? "Alex"}`} description={`${user?.goal.exam ?? "TEF Canada"} preparation · Target ${user?.goal.target ?? "B2"}${user?.goal.targetDate ? ` · ${formatDate(user.goal.targetDate)}` : ""}`} />
    <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><Card className="overflow-hidden border-primary/20 bg-primary text-primary-foreground"><CardContent className="relative pt-6"><div className="absolute -right-10 -top-16 size-52 rounded-full bg-white/10" /><Badge className="border-white/15 bg-white/10 text-white">Recommended next action</Badge><span className="mt-7 grid size-11 place-items-center rounded-xl bg-white/10"><Headphones className="size-5" /></span><h2 className="mt-5 text-2xl font-bold">{recommendation.title}</h2><p className="mt-3 max-w-xl text-sm leading-6 opacity-80">{recommendation.reason}</p><Button asChild variant="secondary" className="mt-7"><Link href={recommendation.href}>Start 10-minute practice <ArrowRight className="size-4" /></Link></Button></CardContent></Card><Card><CardHeader><div className="flex items-center justify-between"><div><p className="text-sm font-bold">MPK Readiness</p><p className="mt-1 text-xs text-muted-foreground">Preparation indicator</p></div><TrendingUp className="size-5 text-primary" /></div></CardHeader><CardContent>{readiness.overall === null ? <><p className="text-2xl font-bold">Not enough data yet</p><p className="mt-3 text-sm leading-6 text-muted-foreground">Complete more practice and at least one simulation to unlock your indicator.</p></> : <><div className="flex items-baseline gap-2"><strong className="text-5xl tracking-tight">{readiness.overall}%</strong><span className="text-sm font-semibold text-primary">+{readiness.trend}%</span></div><Progress value={readiness.overall} label={`MPK readiness ${readiness.overall}%`} className="mt-5" /><p className="mt-4 flex gap-2 text-xs leading-5 text-muted-foreground"><Info className="size-4 shrink-0" />Not an official TEF/TCF score or immigration outcome.</p></>}</CardContent></Card></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-[1fr_.8fr]"><Card><CardHeader><h2 className="text-lg font-bold">Competency snapshot</h2><p className="text-sm text-muted-foreground">Based on recent answers</p></CardHeader><CardContent className="space-y-5">{competencies.map((competency) => <MetricBar key={competency.id} label={competency.label} value={competency.score} status={competency.score >= 75 ? "Strong" : competency.score >= 65 ? "Developing" : "Needs work"} />)}</CardContent></Card><div className="space-y-5"><Card><CardHeader><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Course progress</h2><strong>{state.progress.courseCompletion}%</strong></div></CardHeader><CardContent><Progress value={state.progress.courseCompletion} label="Course completion" /><div className="mt-5 grid grid-cols-2 gap-4 text-sm"><div><p className="text-muted-foreground">Lessons</p><strong>{state.progress.completedLessonIds.length} completed</strong></div><div><p className="text-muted-foreground">Quiz average</p><strong>{state.progress.quizAverage}%</strong></div></div></CardContent></Card><Card><CardHeader><h2 className="text-lg font-bold">Continue learning</h2></CardHeader><CardContent><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-learn/10 text-learn"><BookOpen className="size-5" /></span><div><p className="font-bold">Understanding connectors</p><p className="mt-1 text-sm text-muted-foreground">Core Grammar · 18 min</p></div></div><Button asChild variant="secondary" className="mt-5 w-full"><Link href="/learn/core-grammar/connectors">Resume lesson</Link></Button></CardContent></Card></div></div>
    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card><CardHeader><h2 className="text-lg font-bold">Top weaknesses</h2></CardHeader><CardContent className="space-y-5">{competencies.slice().sort((a,b) => a.score-b.score).slice(0,3).map((item) => <div key={item.id} className="flex items-start justify-between gap-4 border-b pb-4 last:border-0 last:pb-0"><div><p className="font-semibold">{item.label}</p><p className="mt-1 text-xs text-muted-foreground">{item.score}% across {item.attempts} recent questions</p></div><Link href="/practice/session" className="text-xs font-bold text-primary hover:underline">Practice</Link></div>)}</CardContent></Card><Card><CardHeader><h2 className="text-lg font-bold">Recent activity</h2></CardHeader><CardContent className="space-y-5">{state.activities.slice(0,4).map((activity) => <div key={activity.id} className="flex gap-3"><span className="mt-0.5 grid size-8 shrink-0 place-items-center rounded-full bg-muted"><CalendarDays className="size-4 text-primary" /></span><div><p className="text-sm font-semibold">{activity.label}</p><p className="mt-1 text-xs text-muted-foreground">{activity.detail}</p></div></div>)}</CardContent></Card></div></>;
}
