"use client";
import Link from "next/link";
import { ArrowRight, RotateCcw, Target } from "lucide-react";
import { useApp } from "@/components/providers/app-provider";
import { EmptyState, PageHeader } from "@/components/shared";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
const weaknessData = [{ title: "Listening — Specific details", accuracy: 54, evidence: "12 recent questions", action: "Practice detail identification" }, { title: "Time expressions", accuracy: 61, evidence: "8 recent questions", action: "Review depuis / pendant / il y a" }, { title: "Reading inference", accuracy: 65, evidence: "9 recent questions", action: "Practice evidence-based inference" }];
export default function WeaknessesPage() { const { state } = useApp(); return <><PageHeader eyebrow="Mistake engine" title="Your Weakness Profile" description="A ranked view of patterns in your recent answers, with evidence and one clear action for each." action={<Button asChild><Link href="/practice/session">Practice top weakness</Link></Button>} /><div className="grid gap-4 lg:grid-cols-3">{weaknessData.map((item, index) => <Card key={item.title} className={index === 0 ? "border-accent/30" : ""}><CardContent className="pt-6"><div className="flex items-center justify-between"><Badge>Priority {index + 1}</Badge><Target className="size-5 text-accent" /></div><h2 className="mt-5 font-bold">{item.title}</h2><div className="mt-4 flex items-baseline justify-between"><strong className="text-3xl">{item.accuracy}%</strong><span className="text-xs text-muted-foreground">{item.evidence}</span></div><Progress value={item.accuracy} label={`${item.title} accuracy`} className="mt-3" /><p className="mt-5 text-xs font-bold uppercase tracking-wider text-muted-foreground">Recommended</p><p className="mt-2 text-sm font-semibold">{item.action}</p><Button asChild variant="secondary" className="mt-5 w-full"><Link href="/practice/session">Start practice <ArrowRight className="size-4" /></Link></Button></CardContent></Card>)}</div><div className="mt-10 flex items-center justify-between"><div><h2 className="text-xl font-bold">Review mistakes</h2><p className="mt-1 text-sm text-muted-foreground">Previously missed questions and the reasoning behind them.</p></div><Badge>{state.mistakes.length} to review</Badge></div>{state.mistakes.length === 0 ? <div className="mt-5"><EmptyState title="No mistakes to review" description="Complete a practice session and any missed questions will appear here." /></div> : <div className="mt-5 space-y-4">{state.mistakes.map((mistake) => <Card key={mistake.id}><CardContent className="flex flex-col gap-5 pt-5 sm:flex-row sm:items-start sm:justify-between sm:pt-6"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-accent/10 text-accent"><RotateCcw className="size-4" /></span><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-bold">{mistake.mistakeCategory}</h3><Badge>{mistake.reviewStatus}</Badge></div><p className="mt-2 text-sm"><span className="text-muted-foreground">Your answer:</span> {mistake.learnerAnswer}</p><p className="mt-1 text-sm"><span className="text-muted-foreground">Correct answer:</span> <strong>{mistake.correctAnswer}</strong></p><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{mistake.explanation}</p></div></div><Button variant="secondary" size="sm">Mark reviewed</Button></CardContent></Card>)}</div>}</>; }
