"use client";
import { Award, Download, LockKeyhole } from "lucide-react";
import { useApp } from "@/components/providers/app-provider";
import { PageHeader } from "@/components/shared";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { productConfig } from "@/config/product";
import { mockCourse } from "@/data/course";
import { isCertificateEligible } from "@/lib/domain/certificate";
export default function CertificatePage() { const { state } = useApp(); const eligible = isCertificateEligible(mockCourse, state.progress); return <><PageHeader eyebrow="Course completion" title="Certificate" description="A record of completing the MPK Academy curriculum and required checkpoints." />{eligible ? <Card className="mx-auto max-w-4xl border-primary/30"><CardContent className="p-8 text-center sm:p-14"><Award className="mx-auto size-14 text-primary" /><p className="mt-7 text-sm font-bold uppercase tracking-[.2em] text-primary">MPK Academy</p><h2 className="mt-5 text-4xl font-black tracking-tight">Certificate of Completion</h2><p className="mt-4 text-lg">French for Canadian Immigration — TEF/TCF Preparation</p><p className="mt-10 text-sm text-muted-foreground">Presented to</p><p className="mt-2 text-2xl font-bold">{state.user?.firstName} {state.user?.lastName}</p><div className="mx-auto mt-10 grid max-w-xl gap-5 border-y py-6 text-sm sm:grid-cols-2"><div><p className="text-muted-foreground">Completion date</p><strong>August 30, 2026</strong></div><div><p className="text-muted-foreground">Certificate ID</p><strong>MPK-2026-A7K29</strong></div></div><p className="mx-auto mt-7 max-w-2xl text-xs leading-5 text-muted-foreground">{productConfig.certificateDisclaimer}</p><Button className="mt-7" onClick={() => window.print()}><Download className="size-4" />Print or save</Button></CardContent></Card> : <Card className="mx-auto max-w-2xl"><CardContent className="py-12 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-muted"><LockKeyhole className="size-5 text-muted-foreground" /></span><h2 className="mt-5 text-xl font-bold">Certificate not available yet</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-muted-foreground">Complete all required lessons and quizzes with an average of at least 70% to become eligible.</p><div className="mx-auto mt-7 max-w-sm rounded-xl bg-muted p-4 text-left text-sm"><div className="flex justify-between"><span>Course completion</span><strong>{state.progress.courseCompletion}%</strong></div><div className="mt-3 flex justify-between"><span>Quiz average</span><strong>{state.progress.quizAverage}%</strong></div></div></CardContent></Card>}</>; }
