"use client";
import Link from "next/link";
import { Clock3, FileQuestion, Headphones, ShieldCheck } from "lucide-react";
import { useApp } from "@/components/providers/app-provider";
import { LockedContent, ModeBadge, PageHeader } from "@/components/shared";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { canAccessExam } from "@/lib/domain/access";
export default function ExamPage() { const { state } = useApp(); if (!canAccessExam(state.user?.tier ?? "visitor")) return <><PageHeader eyebrow="Exam Mode" title="Measure independent performance." description="French-first simulations are included in the full program." /><LockedContent title="Unlock Exam Mode" /></>; return <><PageHeader eyebrow="Exam simulation" title="Perform independently." description="Experience a focused, timed environment. Instructional assistance is disabled during each attempt and returns only after submission." action={<ModeBadge mode="exam" />} /><div className="grid gap-5 md:grid-cols-3">{[[FileQuestion,"8 questions","Reading, listening, grammar"],[Clock3,"25 minutes","Timed but navigable"],[Headphones,"French-first","No English help in attempt"]].map(([Icon,title,copy]) => { const I = Icon as typeof Clock3; return <Card key={String(title)}><CardContent className="pt-6"><I className="size-5 text-exam" /><p className="mt-4 font-bold">{String(title)}</p><p className="mt-1 text-sm text-muted-foreground">{String(copy)}</p></CardContent></Card>;})}</div><Card className="mt-6 border-exam/20 bg-exam/5"><CardContent className="flex flex-col gap-5 pt-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-exam text-white"><ShieldCheck className="size-5" /></span><div><h2 className="font-bold">Ready for a simulation?</h2><p className="mt-1 text-sm leading-6 text-muted-foreground">Review the format and choose your exam before the timer begins.</p></div></div><Button asChild><Link href="/exam/setup">Set up simulation</Link></Button></CardContent></Card></>; }
