"use client";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { useApp } from "@/components/providers/app-provider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const schema = z.object({ firstName: z.string().min(2), lastName: z.string().min(2), email: z.email(), locale: z.enum(["en","fr"]), assistance: z.enum(["full","on_request","minimal"]), exam: z.enum(["TEF Canada","TCF Canada","Not sure yet"]), target: z.enum(["B1","B2","C1"]), targetDate: z.string().optional() });
type Values = z.infer<typeof schema>;
const select = "mt-2 min-h-11 w-full rounded-xl border bg-background px-3 text-sm focus:border-primary focus:ring-2 focus:ring-primary/15";
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block text-sm font-semibold">{label}{children}</label>; }
export function SettingsForm() { const { state, updateUser, setLocale } = useApp(); const user = state.user; const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { firstName: user?.firstName ?? "Alex", lastName: user?.lastName ?? "Morgan", email: user?.email ?? "alex@demo.mpk", locale: user?.locale ?? "en", assistance: user?.assistance ?? "full", exam: user?.goal.exam ?? "TEF Canada", target: user?.goal.target ?? "B2", targetDate: user?.goal.targetDate ?? "" } }); useEffect(() => { if (user) form.reset({ firstName: user.firstName, lastName: user.lastName, email: user.email, locale: user.locale, assistance: user.assistance, exam: user.goal.exam, target: user.goal.target, targetDate: user.goal.targetDate ?? "" }); }, [user, form]); const submit = (values: Values) => { if (!user) return; updateUser({ ...user, firstName: values.firstName, lastName: values.lastName, email: values.email, locale: values.locale, assistance: values.assistance, goal: { exam: values.exam, target: values.target, targetDate: values.targetDate || undefined } }); setLocale(values.locale); toast.success("Settings saved"); };
  return <form onSubmit={form.handleSubmit(submit)} className="space-y-8"><section className="rounded-2xl border bg-card p-5 sm:p-7"><h2 className="text-lg font-bold">Profile</h2><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="First name"><Input className="mt-2" {...form.register("firstName")} /></Field><Field label="Last name"><Input className="mt-2" {...form.register("lastName")} /></Field><Field label="Email"><Input className="mt-2" type="email" {...form.register("email")} /></Field></div></section><section className="rounded-2xl border bg-card p-5 sm:p-7"><h2 className="text-lg font-bold">Learning preferences</h2><p className="mt-2 text-sm text-muted-foreground">These choices affect instruction and correction. Exam Mode always remains French-first.</p><div className="mt-5 grid gap-5 sm:grid-cols-2"><Field label="Instructional support language"><select className={select} {...form.register("locale")}><option value="en">English</option><option value="fr">Français</option></select></Field><Field label="English assistance"><select className={select} {...form.register("assistance")}><option value="full">Full support</option><option value="on_request">Only when requested</option><option value="minimal">Minimal support</option></select></Field></div></section><section className="rounded-2xl border bg-card p-5 sm:p-7"><h2 className="text-lg font-bold">Exam goal</h2><div className="mt-5 grid gap-5 sm:grid-cols-3"><Field label="Exam"><select className={select} {...form.register("exam")}><option>TEF Canada</option><option>TCF Canada</option><option>Not sure yet</option></select></Field><Field label="Target level"><select className={select} {...form.register("target")}><option>B1</option><option>B2</option><option>C1</option></select></Field><Field label="Target date (optional)"><Input className="mt-2" type="date" {...form.register("targetDate")} /></Field></div></section><section className="rounded-2xl border bg-card p-5 sm:p-7"><h2 className="text-lg font-bold">Account & privacy</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Mock data is stored only in this browser. Production account export, deletion, consent, and privacy controls require a secure backend.</p></section><Button type="submit" size="lg">Save changes</Button></form>;
}
