import Link from "next/link";
import { ArrowRight, LockKeyhole, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";

export function Wordmark() { return <Link href="/" className="inline-flex items-baseline gap-1.5 rounded-lg focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><span className="text-xl font-black tracking-[-.04em]">MPK</span><span className="text-sm font-semibold text-primary">Academy</span></Link>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow?: string; title: string; description?: string; action?: React.ReactNode }) { return <header className="mb-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div className="max-w-2xl">{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">{title}</h1>{description && <p className="mt-3 text-base leading-7 text-muted-foreground">{description}</p>}</div>{action}</header>; }
export function ModeBadge({ mode }: { mode: "learn" | "practice" | "exam" }) { const values = { learn: ["Learn with support", "bg-learn/10 text-learn border-learn/20"], practice: ["Apply what you learned", "bg-practice/10 text-practice border-practice/20"], exam: ["Perform independently", "bg-exam/10 text-exam border-exam/20"] } as const; return <Badge className={values[mode][1]}>{values[mode][0]}</Badge>; }
export function Stat({ label, value, detail }: { label: string; value: string; detail?: string }) { return <Card><CardContent className="pt-5 sm:pt-6"><p className="text-sm font-medium text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold tracking-tight">{value}</p>{detail && <p className="mt-2 text-sm text-muted-foreground">{detail}</p>}</CardContent></Card>; }
export function MetricBar({ label, value, status }: { label: string; value: number; status?: string }) { return <div><div className="mb-2 flex items-center justify-between gap-3 text-sm"><span className="font-medium">{label}</span><span className="text-muted-foreground">{status ?? `${value}%`}</span></div><Progress value={value} label={`${label}: ${value}%`} /></div>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <Card className="border-dashed"><CardContent className="flex flex-col items-center py-12 text-center"><span className="mb-4 grid size-11 place-items-center rounded-full bg-muted"><Sparkles className="size-5 text-primary" /></span><h3 className="font-bold">{title}</h3><p className="mt-2 max-w-md text-sm leading-6 text-muted-foreground">{description}</p></CardContent></Card>; }
export function LockedContent({ title = "Included in the full program" }: { title?: string }) { return <Card className="bg-muted/50"><CardContent className="flex flex-col items-start gap-4 pt-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-full bg-card"><LockKeyhole className="size-5 text-primary" /></span><div><h3 className="font-bold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">Unlock the complete curriculum, targeted practice, and exam simulations.</p></div></div><Button asChild><Link href="/checkout">View full program <ArrowRight className="size-4" /></Link></Button></CardContent></Card>; }
