import Link from "next/link";
import { ArrowRight, BookOpenCheck, Brain, ChartNoAxesColumnIncreasing, Check, CircleGauge, Headphones, Languages, ShieldCheck, Target } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { formatPrice } from "@/config/product";

const loop = ["Set your goal", "Diagnose", "Learn", "Practice", "Simulate", "Measure", "Adapt", "Repeat"];
const differences = [
  { icon: Languages, title: "English support, precisely when useful", copy: "Understand instructions and corrections clearly, then gradually reduce support as your confidence grows." },
  { icon: Brain, title: "A plan built from evidence", copy: "MPK tracks the competencies and mistake patterns behind each answer—not only a total score." },
  { icon: Target, title: "Always know what to do next", copy: "Recommendations connect your recent performance to one focused lesson, practice set, or simulation." },
];
const modes = [
  { icon: BookOpenCheck, label: "Learning Mode", title: "Learn with support", copy: "French examples, clear explanations, vocabulary, and guided checkpoints." },
  { icon: Target, label: "Practice Mode", title: "Apply what you learned", copy: "Focused questions, immediate feedback, and mistake-aware review." },
  { icon: ShieldCheck, label: "Exam Mode", title: "Perform independently", copy: "Timed, French-first simulations without hints or in-attempt correction." },
];

export default function HomePage() {
  return <>
    <section className="relative overflow-hidden py-20 sm:py-28"><div className="absolute -right-32 top-10 size-96 rounded-full bg-primary/10 blur-3xl" /><div className="container-page relative grid items-center gap-14 lg:grid-cols-[1.15fr_.85fr]"><div><Badge className="border-primary/20 bg-primary/10 text-primary">French for Canadian immigration</Badge><h1 className="mt-7 max-w-3xl text-5xl font-black leading-[1.04] tracking-[-.045em] sm:text-6xl">Prepare for TEF/TCF with a plan built around <span className="text-primary">your weaknesses.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-muted-foreground">Learn French with English explanations when you need them, strengthen the skills holding you back, then transition into an authentic French-first exam environment.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><Link href="/diagnostic">Start free diagnostic <ArrowRight className="size-4" /></Link></Button><Button asChild size="lg" variant="secondary"><Link href="/program">Explore the program</Link></Button></div><p className="mt-4 text-xs text-muted-foreground">Free · About 10 minutes · No card required</p></div><Card className="relative overflow-hidden border-primary/15 bg-card/90 p-2"><div className="rounded-xl bg-ink p-6 text-white sm:p-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-white/60">Your next best action</p><span className="mt-6 grid size-12 place-items-center rounded-full bg-white/10"><Headphones /></span><h2 className="mt-5 text-2xl font-bold">Practice listening for detail</h2><p className="mt-3 leading-7 text-white/70">You missed 5 of your last 8 questions involving specific details.</p><div className="mt-7 rounded-xl bg-white/10 p-4"><div className="flex justify-between text-sm"><span>MPK Readiness</span><strong>72%</strong></div><div className="mt-3 h-2 rounded-full bg-white/10"><div className="h-2 w-[72%] rounded-full bg-[#74dab8]" /></div><p className="mt-3 text-xs text-white/55">Preparation indicator · not an official TEF/TCF score</p></div></div></Card></div></section>
    <section className="border-y bg-card py-12"><div className="container-page"><p className="text-center text-sm font-bold text-muted-foreground">THE MPK LEARNING LOOP</p><ol className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-8">{loop.map((item, index) => <li key={item} className="flex items-center gap-2 text-sm font-semibold"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-primary/10 text-xs text-primary">{index + 1}</span>{item}</li>)}</ol></div></section>
    <section className="container-page py-24"><div className="mx-auto max-w-2xl text-center"><p className="eyebrow">Why MPK is different</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Clarity while learning. Independence when it counts.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{differences.map(({ icon: Icon, title, copy }) => <Card key={title}><CardContent className="pt-6"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></span><h3 className="mt-5 text-lg font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy}</p></CardContent></Card>)}</div></section>
    <section className="bg-ink py-24 text-white"><div className="container-page"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#74dab8]">Three deliberate modes</p><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Support decreases as performance becomes the goal.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-3">{modes.map(({ icon: Icon, label, title, copy }, index) => <article key={title} className="rounded-2xl border border-white/10 bg-white/[.05] p-6"><div className="flex items-center justify-between"><Icon className="size-6 text-[#74dab8]" /><span className="text-xs text-white/45">0{index + 1}</span></div><p className="mt-8 text-xs font-bold uppercase tracking-wider text-white/50">{label}</p><h3 className="mt-2 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/65">{copy}</p></article>)}</div></div></section>
    <section id="how-it-works" className="container-page py-24"><div className="grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">How it works</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">From uncertainty to a focused weekly plan.</h2><p className="mt-5 max-w-xl leading-7 text-muted-foreground">Start with a short diagnostic. MPK turns performance into a competency profile, then connects each weak point to the right learning activity.</p></div><div className="space-y-7">{[[CircleGauge,"Diagnose your current level","See a six-competency breakdown—not just one number."],[Brain,"Work on the evidence","Learn and practice the patterns appearing in your mistakes."],[ChartNoAxesColumnIncreasing,"Measure readiness","Use activity and simulations to understand preparation trends."]].map(([Icon,title,copy], i) => { const I = Icon as typeof Brain; return <div key={String(title)} className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-primary text-primary-foreground"><I className="size-5" /></span><div><h3 className="font-bold">{i + 1}. {String(title)}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{String(copy)}</p></div></div>;})}</div></div></section>
    <section className="border-y bg-card py-24"><div className="container-page grid gap-12 lg:grid-cols-[1fr_.9fr]"><div><p className="eyebrow">The complete program</p><h2 className="mt-3 text-3xl font-bold tracking-tight">Eight modules from foundation to simulation.</h2><div className="mt-7 grid gap-3 sm:grid-cols-2">{["Exam orientation","Core grammar","Exam vocabulary","Reading comprehension","Listening comprehension","Question strategies","Timed practice","Final preparation"].map((item) => <p key={item} className="flex gap-2 text-sm"><Check className="size-5 shrink-0 text-primary" />{item}</p>)}</div></div><Card><CardContent className="pt-6"><Badge>One-time purchase</Badge><p className="mt-5 text-4xl font-black">{formatPrice()}</p><p className="mt-2 text-sm text-muted-foreground">Complete TEF/TCF preparation program</p><Button asChild className="mt-7 w-full"><Link href="/checkout">Get the full program</Link></Button><p className="mt-4 text-center text-xs text-muted-foreground">Mock checkout · no real payment is collected</p></CardContent></Card></div></section>
    <section className="container-page py-24"><div className="mx-auto max-w-3xl"><p className="eyebrow text-center">FAQ</p><h2 className="mt-3 text-center text-3xl font-bold">Questions before you begin</h2><div className="mt-10 divide-y border-y">{[["Is MPK an official TEF/TCF provider?","No. MPK Academy provides independent preparation material and does not administer or represent either exam."],["Will MPK predict my official score?","No. MPK Readiness is an internal preparation indicator based only on your activity in the platform."],["Can I learn with explanations in English?","Yes. Navigation and instructional support can be English or French. Exam Mode remains French-first."],["Is this a subscription?","No. The MVP presents the complete program as a one-time purchase."]].map(([q,a]) => <details key={q} className="group py-5"><summary className="cursor-pointer list-none font-bold">{q}<span className="float-right text-primary group-open:rotate-45">+</span></summary><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{a}</p></details>)}</div></div></section>
    <section className="container-page"><div className="overflow-hidden rounded-3xl bg-primary px-6 py-14 text-center text-primary-foreground sm:px-12"><h2 className="text-3xl font-bold tracking-tight">Find the skill holding you back.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-6 opacity-80">Take the free diagnostic and leave with a clear starting point—whether or not you join the full program.</p><Button asChild size="lg" variant="secondary" className="mt-7"><Link href="/diagnostic">Start free diagnostic <ArrowRight className="size-4" /></Link></Button></div></section>
  </>;
}
