"use client";
import Link from "next/link";
import { CheckCircle2, ChevronRight, Clock3, LockKeyhole } from "lucide-react";
import { useApp } from "@/components/providers/app-provider";
import { ModeBadge, PageHeader } from "@/components/shared";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { courseModules } from "@/data/course";
export default function LearnPage() { const { state } = useApp(); return <><PageHeader eyebrow="Your course" title="Build the French you need for the exam." description="Follow the recommended path or revisit a skill. Explanations stay clear; French performance stays central." action={<ModeBadge mode="learn" />} /><Card className="mb-7"><CardContent className="flex flex-col gap-4 pt-5 sm:flex-row sm:items-center"><div className="flex-1"><div className="flex justify-between text-sm"><strong>Overall course completion</strong><span>{state.progress.courseCompletion}%</span></div><Progress value={state.progress.courseCompletion} label="Course completion" className="mt-3" /></div><Badge>{state.progress.completedLessonIds.length} lessons completed</Badge></CardContent></Card><div className="space-y-4">{courseModules.map((module) => { const locked = module.sequence > 2 && state.user?.tier !== "paid_student"; return <Card key={module.id} className={locked ? "bg-muted/40" : ""}><CardContent className="grid gap-4 pt-5 sm:grid-cols-[auto_1fr_auto] sm:items-center sm:pt-6"><span className="grid size-11 place-items-center rounded-full bg-learn/10 font-bold text-learn">{module.sequence}</span><div><div className="flex items-center gap-2"><h2 className="font-bold">{module.title}</h2>{module.sequence === 1 && <Badge>Free</Badge>}</div><p className="mt-1 text-sm text-muted-foreground">{module.description}</p><p className="mt-3 flex items-center gap-2 text-xs text-muted-foreground"><Clock3 className="size-4" />{module.lessons.reduce((sum, item) => sum + item.duration, 0)} min · {module.lessons.length} lessons</p></div>{locked ? <LockKeyhole className="size-5 text-muted-foreground" /> : state.progress.completedLessonIds.includes(module.lessons.at(-1)?.id ?? "") ? <CheckCircle2 className="size-5 text-primary" /> : <Link href={`/learn/${module.id}`} aria-label={`Open ${module.title}`} className="rounded-lg p-2 text-primary hover:bg-muted"><ChevronRight /></Link>}</CardContent></Card>; })}</div></>; }
